### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by Viddesh1** [Sreenathkk00/PawsomePicks_E-com#1]
Hello @Sreenathkk00 ,

Great work!. Thanks for creating this project. 

I was just messing with the codebase. While reading through the readme file i counter at the end of the readme.md file it says " This project is licensed under the [MIT License](LICENSE). " But, the license is missing.

Regards!
Viddesh

**Comment by sreenath-pydev** [comment]
*Subject*: Apologies for the oversight, the issue has been resolved!

Hello Viddesh,

Thank you for pointing that out, and I appreciate your attention to detail!

I apologize for the oversight regarding the missing license file. The issue
has now been resolved, and the MIT License has been added to the project.
You can check it out in the repository.

Please feel free to review the code and let me know if you encounter any
further issues or have any feedback.

Thanks again for bringing this to my attention!

Best regards,
Sreenath K K (https://github.com/Sreenathkk00)
